LR-8436. Add support of laravel 11.0.
Insly/phpunit-coverage-check pull request #2
Opened 2024-10-28 12:41 UTC by rafaelemi

2024-11-11 13:00 UTC, daenoor requested changes
Tests are failing when run locally
<img width="1440" alt="Screenshot 2024-11-11 at 14 59 53" src="https://github.com/user-attachments/assets/d801764b-917e-47bc-9588-8abf0b419fe6">

2024-11-12 13:26 UTC, rafaelemi commented
> Tests are failing when run locally <img alt="Screenshot 2024-11-11 at 14 59 53" width="1440" src="https://private-user-images.githubusercontent.com/211334/384929939-d801764b-917e-47bc-9588-8abf0b419fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTgyNjQsIm5iZiI6MTczMTQxNzk2NCwicGF0aCI6Ii8yMTEzMzQvMzg0OTI5OTM5LWQ4MDE3NjRiLTkxN2UtNDdiYy05NTg4LThhYmYwYjQxOWZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQxMzI2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjA4MGFmMjJiMDQ0ZmVlYjdhNDA2MDRiZTExMDExYmEzYWFlODIyNTE3ZTg5MmU0Y2E0NzgzZGY4MGJhZWU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mG1z-e9xLQ_y6cuieTvd8dbj9gAH8F0pUmDD7vwaiN4">

tests are fixed.

2024-11-13 07:47 UTC, daenoor approved these changes

2024-11-13 07:47 UTC, daenoor commented on composer.json
> +        "symfony/console": "^6.0|^7.1.6"
`|` should be `||`

2025-01-15 08:54 UTC, AMalevichBS approved these changes

2025-03-20 13:51 UTC, merged